Feature user api 기능 구현
OZ-Coding-School/oz_03_main-001-BE pull request #25
Opened 2024-07-31 02:42 UTC by Gomnonix

**변경 사항 요약**

변경 사항에 대한 간단한 설명을 작성해주세요.

**연결된 이슈**

**변경 유형**
- [ 0] 버그 수정 (기존 기능 수정)
- [ 0] 새로운 기능 (새로운 기능 추가)
- [ 0] 기타 (문서 수정, 스타일 수정 등)

**체크리스트**
- [ 0] 코드가 프로젝트의 스타일 가이드를 따릅니다.
- [ 0] 변경 사항이 문서에 반영되었습니다.
- [ 0] 새로운 경고를 생성하지 않습니다.
- [ 0] 관련된 이슈가 해결되었습니다.

**추가 정보**

추가적인 정보나 스크린샷을 여기에 포함해주세요.

2024-07-31 02:48 UTC, ChoiWheatley requested changes
settings/base.py에 `SECRET_KEY` 부분을 .env로 빼주세요. 브랜치로 올라갔던 "insecure..." 문자열이 아닌, django-admin을 사용하여 새 시크릿 키를 만들어주세요.

To generate a new secret key without creating a temporary Django project, I can use a Python script to generate a suitable random secret key.

```
python -c 'from django.core.management.utils import get_random_secret_key; print(get_random_secret_key())'
```

2024-07-31 03:07 UTC, ChoiWheatley requested changes

2024-07-31 03:07 UTC, ChoiWheatley commented on oauth/tests.py
> +        self.kakao_client_secret_env = 'lsklWvQBeUu3osttxNlgZlmkuXifek19'
카카오 클라이언트 비밀키가 노출되었습니다. 새 비밀키를 발급받으시고 .env로 빼주시기 바랍니다.

2024-07-31 03:07 UTC, ChoiWheatley commented on oauth/tests.py
> +        self.kakao_redirect_uri_env = 'http://127.0.0.1:8000/v1/users/kakao/callback/'
백엔드 배포링크를 .env로 뺀다면 프로덕션 환경과 개발 환경 따로 uri를 설정할 수 있습니다.

2024-07-31 03:07 UTC, ChoiWheatley commented on users/views.py
> +        user = User.objects.get(pk=pk)
`/users/1` 과 같이 엔드포인트로 접근하게 되면 로그인 여부와 상관없이 사용자 정보를 볼 수 있고 수정할 수 있는 보안 이슈가 발생하게 됩니다. Authorization 헤더를 통해 인가를 수행하는 코드를 작성해주세요.

2024-07-31 03:07 UTC, ChoiWheatley commented on users/views.py
> +    def put(self, request, pk, *args, **kwargs):
Authorization 헤더를 통해 인가를 수행하는 코드를 작성해주세요.

2024-07-31 03:07 UTC, ChoiWheatley commented on users/views.py
> +    def delete(self, request, pk, *args, **kwargs):
Authorization 헤더를 통해 인가를 수행하는 코드를 작성해주세요.

2024-07-31 10:31 UTC, ChoiWheatley approved these changes
LGTM

2024-08-01 06:59 UTC, im-niber approved these changes
테스트 부분 같이 적용하면서 다 확인했어서,  바로 머지하셔도 될거 같습니다 !

2024-08-01 06:59 UTC, im-niber commented on .github/workflows/ci.yml
> -
views.py 파일 내부에 타입 선언 하시구 다시 mypy 추가해주세요~~ test 부분은 mypy 검사 제외해뒀어서 금방 하실검니당

2024-08-01 06:59 UTC, im-niber commented on users/tests.py
> +    #     self.assertEqual(response.data["allergies"], {"메밀": True, "밀": True})
주석은 삭제해주세요 !

2024-08-01 06:59 UTC, im-niber commented on users/tests.py
> +        self.client.force_authenticate(user=self.test_user)
이 부분 빼시구 토큰 발급하는 코드를 setup에서 진행하고, 헤더에 추가해서 테스트 해주세요 !

2024-08-01 06:59 UTC, im-niber commented on .gitignore
> +
이 부분 문서보니까 커밋하는걸 권장해서 나중에 develop 브랜치에서 따로 제가 수정해서 푸쉬할게여

2024-08-01 07:00 UTC, merged